### ISSUE TITLE
Question about retrieving collections and schemes + questions on FoLiA Set Definition interoperability

### ISSUE THREAD

**Issue by proycon** [OpenSKOS/OpenSKOS#65]
I couldn't find this in the documentation so would like to ask it here: 

* Can I retrieve a SKOS Collection by URI?
* Can I retrieve all concepts pertaining to a collection?
* Can I retrieve all collections pertaining to a collection? 
* Can I retrieve a SKOS ConceptScheme by URI?
* Can I retrieve all concepts pertaining to a concept scheme? 

When I try to query a collection by URI through ``find-concepts?id=`` (not sure if that's supposed to work, it's not a concept after all), I encounter issue #64

**Comment by olhsha** [comment]
Similar and other examples are given in https://github.com/OpenSKOS/OpenSKOS/blob/developMeertens/README.md

Anyway I answer your questions  one by one:

Q: Can I retrieve a SKOS Collection by URI?
A: yes, e.g. http://145.100.58.79/ccr/public/api/skoscollection?id=http://hdl.handle.net/11148/CCR__cc113862-9920-2c33-8904-c1f248a3fefe

Q: Can I retrieve all concepts pertaining to a collection?
A: yes, e.g. http://145.100.58.79/ccr/public/api/find-concepts?q=prefLabel:*&skosCollection=http://hdl.handle.net/11148/CCR__cc113862-9920-2c33-8904-c1f248a3fefe

Q: Can I retrieve all collections pertaining to a collection?
A: No.  @menzowindhouwer, I think we have not kept in mind collections of collections, have we? Otherwise I will to add an API for it.

Q: Can I retrieve a SKOS ConceptScheme by URI?
A: yes, e.g. http://145.100.58.79/ccr/public/api/conceptscheme?id=http://hdl.handle.net/11148/CCR_P-Metadata_deedbe7e-9a1d-4388-2857-ad0daaf06793

Q: Can I retrieve all concepts pertaining to a concept scheme?
A: yes, e.g. http://145.100.58.79/ccr/public/api/find-concepts?q=prefLabel:*&conceptScheme=http://hdl.handle.net/11148/CCR_P-Metadata_deedbe7e-9a1d-4388-2857-ad0daaf06793

**Comment by proycon** [comment]
Thanks a lot! That'll help me further!

**Comment by olhsha** [comment]
As for collections of collections. Now we have "sets", which gather schemata and skos collections. Sets belong to an institution. May be "sets" is what you mean? Try, for instance,
http://145.100.58.79/clavas/public/api/institution/example.html, then browse form this page to the referred sets and further by the hierarchy. In particular you should be able to find  e.g.
http://145.100.58.79/clavas/public/api/set/clavas-org.html where you have list of collections (if any). Or try http://145.100.58.79/ccr/public/api/set/isocat.html. I'm afraid we do not have URI filtering skos collections by sets which they belong to, but I can add it.

**Comment by menzowindhouwer** [comment]
OpenSKOS doesn't (yet) support nested collections, i.e., collections in collections. But as @olhsha states above it has some additional layer on top of collections and concept schemes. See https://www.clarin.eu/sites/default/files/shkaravska-etal-CLARIN2016_paper_18.pdf for a recent overview.

**Comment by proycon** [comment]
Thanks for the pointers! Perhaps some background info is in order, I'd appreciate any comments on this: I'm working on modelling FoLiA Set Definitions using SKOS (see proycon/folia#14). 

Ideally, it would be nice if people could build these set definitions in the CLARIN Concept Registry and FoLiA applications can pull them directly from there using OpenSKOS. FoLiA documents declare what sets are used for what annotation types, these point to a URL that may just as well be a URL to the OpenSKOS API. For this to work I would need to kind of entry point in the API to retrieve one specific collection, all collections nested inside, and all concepts of both main collection and subcollection, in a single response  (rdf+xml or turtle).

Regarding collections in collections, I didn't realize that wasn't used yet. The more complex set definitions (such as the CGN pos tag set) contains subsets (e.g. gender, case, number) , I planned to  implement these as collections in collections. 

I'm deviating from the original issue but any feedback on this would be greatly appreciated:
* What do you think of my SKOS model for FoLiA Set Definitions (read my last post in proycon/folia#14)
* What do you think of the idea for interoperability with OpenSKOS?

**Comment by olhsha** [comment]
Maarten, I think that Folia's understanding of "sets" is similar to concepts, not skos collections or open-skos sets, because you mean under "sets"  rather *notions* describing certain lists, rather then lists as enumerations of their elements. Correct? So, to express hierarchy between notions (concepts) all you need is SKOS:broader and SKOS:narrower. E.g. "case" has narrower "nominative". Technically it all works. It is easy to post such relations in OpenSKOS 2 if it goes about your own concept registry where you are the boss. However for Clarin Concept Registry we need the agreement of the coordinators to changes something there. We will have meeting soon where we think on your questions in more detail.

**Comment by olhsha** [comment]
Also, check https://www.w3.org/TR/skos-reference/#semantic-relations

Moreover, inn OpenSKOS 2 you can define and submit your own relation. So, if you want to say that a word (as a concept) has PoS "noun" you could express it via relation, e.g. <maarten:hasPoS ref:=uri-of-noun-in-ccr>. But first you have to submit this relation:
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns:rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:openskos = "http://openskos.org/xmlns#"
xmlns:dcterms = "http://purl.org/dc/terms/">
    <rdf:Description rdf:about="http://maartenvg.org/xmlns#hasPoS">
        <dcterms:title>has-part-of-speach</dcterms:title>
    </rdf:Description>
</rdf:RDF>

**Comment by proycon** [comment]
FoLiA sets do have to be explicitly enumerable, even explicitly orderable though my solution for that is not SKOS-based yet and suboptimal. Basically FoLiA sets are like keys in a *key->value store*, fulfilling the role of a notion and a container at the same type, whereas classes correspond to the possible values, on top of that is the modelling of subsets and classes in those subsets to express a kind of higher-order annotation (*features* in FoLiA lingo). The distinction between the keys (sets) and values (classes) is very important here. If I were to express sets as concepts too, I don't really see how I can link a key/set to its possible values/classes without introducing new non-SKOS vocabulary, because at the same time I want to allow for a hierarchy to be expressed for the classes/values, for which I already use ``skos:broader`` (e.g. *"street"* is a narrower version of *"location"*, but not a FoLiA subset  in the context for example this named entities set: https://github.com/proycon/folia/blob/folia1.4/setdefinitions/namedentities.foliaset.ttl).

My main deliberation was whether ``skos:Collection`` or ``skos:ConceptScheme`` would be most suitable, I decided on collections based on the ability to nest them and they seemed most prevalent in the CCR, though I saw a lot of inconsistency there.

Yesterday, I was trying to determine if what's currently in the CCR regarding CGN PoS tags was enough for a proper FoLiA set definition, but the aforementioned distinction between keys/values is precisely what I was missing. I see no relation between *case* (https://openskos.meertens.knaw.nl/ccr/browser/index.php?id=http%3A%2F%2Fhdl.handle.net%2F11459%2FCCR_C-4932_98dfae04-f3f0-0242-d09d-5de1e5762b32) and *nominative* (https://openskos.meertens.knaw.nl/ccr/browser/index.php?id=http%3A%2F%2Fhdl.handle.net%2F11459%2FCCR_C-4934_47f7507c-4606-bb34-0521-b7d50f911769) at all. 

An example of some actual FoLiA XML for a PoS annotation using CGN may be illustrative for this discussion perhaps. The main role of the set definitions is to validate such things:

```xml
<pos set="https://github.com/proycon/folia/blob/folia1.4/setdefinitions/frog-mbpos-cgn" 
  class="WW(pv,tgw,met-t)"> 
  <feat subset="head" class="WW" />
  <feat subset="wvorm" class="pv" />
  <feat subset="pvtijd" class="tgw" />
  <feat subset="pvagr" class="met-t" />
</pos>   
```

> It is easy to post such relations in OpenSKOS 2 if it goes about your own concept registry where 
> you are the boss. However for Clarin Concept Registry we need the agreement of the 
> coordinators to changes something there. We will have meeting soon where we think on your 
> questions in more detail.

I understand yes, it would be good if you can think about my use case in the meeting indeed. I don't really have an interest in running my own OpenSKOS registry; I'm perfectly content just publishing turtle files on github for set definitions, but in a wider CLARIN context integration with the Clarin Concept Registry may be more desirable.

**Comment by proycon** [comment]
Some concluding summary after our meeting: 

* hosting FoLiA Set Definitions inside the CLARIN Concept Registry is not preferred, besides technical obstacles it things would also have to go past coordinators. 
* Proposal was to run a custom OpenSKOS system for hosting FoLiA Set Definitions, but I think that is probably overkill at this stage, and we best continue just hosting set definitions (in RDF form) directly from repositories like github.
* Given the nature of RDF, links from FoLiA set definitions to CCR concepts can always be established explicitly by set creators.
